React capstone project
elyor-doniyorov/favorite-companies pull request #1
Opened 2021-10-12 13:44 UTC by elyor-doniyorov

### Metrics webapp

**In this PR:👇**

- Use React documentation.
- Use React components.
- Use React props.
- Use React Router.
- Connect React and Redux.
- Handle events in a React app.
- Write integration tests with a React testing library.
- Use styles in a React app.
- Use React life cycle methods.
- Apply React best practices and language style guides in code.
- Use store, actions and reducers in React.

2021-10-14 14:29 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-10-14 14:29 UTC, arslanbisharat commented on src/__test__/DetailsPage.test.js
> +import '@testing-library/jest-dom/extend-expect';
- [ ] Let's add more test cases in your project, currently, you have only two cases.

2021-10-14 14:29 UTC, arslanbisharat commented on README.md
> +- Run `npm run start` to launch the server.
- [ ] Let's add how to run test too in your Readme.

2021-10-15 00:11 UTC, mke2111 approved these changes
### Hi @elyor-doniyorov, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-15 05:09 UTC, merged